name: "Agent Workspace Setup"
description: "Sets up a new project based on the agentic-windsurf-template"
version: "1.0.0"
author: "Alex Kamysz"

triggers:
  commands:
    - "setup-agent-workspace"
    - "init-agent-project"
    - "prep-agent-env"
  fuzzy_match: true
  fuzzy_threshold: 0.7

actions:
  setup_from_template:
    type: "custom_command"
    implementation: |
      async function setupFromTemplate(args) {
        // Get destination path (current workspace by default)
        const destPath = args.path || await windsurf.executeCommand('pwd');
        
        // Create a temporary directory for cloning
        const tempDir = `/tmp/template-${Date.now()}`;
        await windsurf.executeCommand(`mkdir -p ${tempDir}`);
        
        try {
          // Clone the template repository to temp directory
          const templateRepo = "https://github.com/arkaigrowth/agentic-windsurf-template";
          await windsurf.executeCommand(`git clone ${templateRepo} ${tempDir}`);
          
          // Copy template contents to destination (excluding .git directory)
          await windsurf.executeCommand(`cp -R ${tempDir}/* ${destPath}/`);
          
          // Copy .windsurf directory but exclude the agent-workspace-setup.yaml file
          await windsurf.executeCommand(`mkdir -p ${destPath}/.windsurf`);
          await windsurf.executeCommand(`cp -R ${tempDir}/.windsurf/* ${destPath}/.windsurf/`);
          
          // If rules directory exists, exclude the agent-workspace-setup.yaml file
          if (await windsurf.executeCommand(`test -d ${tempDir}/.windsurf/rules && echo "exists"`)) {
            await windsurf.executeCommand(`find ${tempDir}/.windsurf/rules -type f -not -name "agent-workspace-setup.yaml" -exec cp {} ${destPath}/.windsurf/rules/ \;`);
          }
          
          // Copy hidden files (except .git)
          await windsurf.executeCommand(`find ${tempDir} -maxdepth 1 -name ".*" -not -name ".git" -exec cp -R {} ${destPath}/ \;`);
          
          // Cleanup temp directory
          await windsurf.executeCommand(`rm -rf ${tempDir}`);
          
          // Open the workspace file if it exists
          if (await windsurf.executeCommand(`test -f ${destPath}/my_windsurf_project.code-workspace && echo "exists"`)) {
            await windsurf.executeCommand(`code ${destPath}/my_windsurf_project.code-workspace`);
          }
          
          return `Template contents copied successfully to ${destPath}`;
        } catch (error) {
          // Clean up on error
          await windsurf.executeCommand(`rm -rf ${tempDir}`);
          return `Error setting up template: ${error.message}`;
        }
      }
